apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
    - name: demo
      image: agrimmer/demo:time
      ports:
        - name: web
          containerPort: 8888
          protocol: TCP