# Pull in the layer of the base image: golang:1.13-alpine


# Set author label: LABEL author=[YOUR-EMAIL]


# Set working directory: `/opt`


# Copy local file `main.go` to the working directory


# List items in the working directory (ls -lsa) and show content of the `main.go`file (cat)


# Build the app (CGO_ENABLED=0 go build -o /usr/myapp) and show the /usr directory  (ls -lsa)
