apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-list-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-list-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-list-reader
  namespace: default
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  labels:
    app.kubernetes.io/name: kubectl-pod
spec:
  serviceAccountName: pod-list-reader
  containers:
    - name: kubectl-container
      image: bitnami/kubectl:latest
      tty: true
      command: ["/bin/sh"]